### ISSUE TITLE
running bug

### ISSUE THREAD

**Issue by GitHub-TXZ** [Graph-Machine-Learning-Group/spin#8]
I ran your demo code by  
python ./experiments/run_imputation.py --config imputation/spin.yaml --model-name spin --dataset-name bay_block

Traceback (most recent call last):
  File "./experiments/run_imputation.py", line 303, in <module>
    run_experiment(args)
  File "./experiments/run_imputation.py", line 172, in run_experiment
    time_emb = dataset.datetime_encoded(['day', 'week']).values
  File "/home/txz/.conda/envs/spin/lib/python3.8/site-packages/tsl/datasets/prototypes/mixin.py", line 83, in datetime_encoded
    mapping = {un: pd.to_timedelta('1' + un).delta
  File "/home/txz/.conda/envs/spin/lib/python3.8/site-packages/tsl/datasets/prototypes/mixin.py", line 83, in <dictcomp>
    mapping = {un: pd.to_timedelta('1' + un).delta
AttributeError: 'Timedelta' object has no attribute 'delta'

**Comment by marshka** [comment]
Hi, this error may be due to the pandas version you are using. Please try with pandas>=1.4.
